using System;
using System.Runtime.Serialization;

namespace GeneralEntities.Services.Hotels.Entities.GroupElements.Static
{
	/// <summary>
	/// особенности отелей
	/// </summary>
	[Flags]
	[DataContract(Namespace = "http://nemo-ibe.com/STL")]
	public enum HotelsFeatures
	{
		//noShowTodo,
		[EnumMember]
		ActivitiesAndSport,
		[EnumMember]
		Amenities,
		[EnumMember]
		Airport,
		[EnumMember]
		Area,
		[EnumMember]
		ATM_Banking,
		[EnumMember]
		Bar,
		[EnumMember]
		BathroomAmenities,
		[EnumMember]
		BeautySalon,
		[EnumMember]
		Bedroom,
		[EnumMember]
		BusinessCenter,
		[EnumMember]
		ConferenceFacilities,
		[EnumMember]
		CheckIn,
		[EnumMember]
		CheckOut,
		[EnumMember]
		Children,
		[EnumMember]
		City,
		[EnumMember]
		ClimateControl,
		[EnumMember]
		Coasts,
		[EnumMember]
		CommonInfo,
		[EnumMember]
		CleaningServices,
		[EnumMember]
		CreditCards,
		[EnumMember]
		DisabledFacilities,
		[EnumMember]
		Elevator,
		[EnumMember]
		Excursions,
		[EnumMember]
		Internet,
		[EnumMember]
		Kitchen,
		[EnumMember]
		Luggage,
		[EnumMember]
		Meal,
		[EnumMember]
		MediaAndTechnologies,
		[EnumMember]
		Medical,
		[EnumMember]
		Message,
		[EnumMember]
		News,
		[EnumMember]
		Parking,
		[EnumMember]
		Pets,
		[EnumMember]
		Rental,
		[EnumMember]
		Restaurant,
		[EnumMember]
		Rooms,
		[EnumMember]
		Safe,
		[EnumMember]
		Security,
		[EnumMember]
		Service,
		[EnumMember]
		Shop,
		[EnumMember]
		Smoking,
		[EnumMember]
		SPA,
		[EnumMember]
		Staff,
		[EnumMember]
		Transfer,
		[EnumMember]
		TicketReservation,
		[EnumMember]
		UnknownFeature,
		[EnumMember]
		Beach,
	}
}
